import {Printer, X} from 'lucide-react'
import {useEffect} from 'react'

const TAB_TITLE = {
	soap: 'SOAP Note',
	icd: 'ICD Coding',
	digitization: 'Digitized Prescription'
}

export function PrintLetterhead({open, tab, html, onClose}) {
	useEffect(() => {
		if (!open) return
		const previous = document.body.style.overflow
		document.body.style.overflow = 'hidden'
		return () => {
			document.body.style.overflow = previous
		}
	}, [open])

	if (!open) return null

	return (
		<div className='tp-print-root'>
			<div className='tp-print-controls'>
				<div className='font-display text-base font-semibold' style={{color: 'var(--tp-slate-900)'}}>
					Print preview — {TAB_TITLE[tab] || tab}
				</div>
				<div className='flex items-center gap-2'>
					<button type='button' className='tp-btn-primary' onClick={() => window.print()}>
						<Printer className='h-4 w-4'/>
						<span>Print</span>
					</button>
					<button type='button' className='tp-btn-secondary' onClick={onClose}>
						<X className='h-4 w-4'/>
						<span>Close</span>
					</button>
				</div>
			</div>

			<div className='flex-1 overflow-y-auto' style={{background: 'var(--tp-slate-100)'}}>
				<div className='tp-print-frame'>
					<header className='tp-print-letterhead'>
						<div>
							<h1>Tatva Care Hospital</h1>
							<div className='tp-print-clinic-meta'>
								501–504, Trade Centre, Stadium Road, Navrangpura, Ahmedabad — 380009<br/>
								Phone: +91-79-1234-5678 · Email: care@tatvacare.in
							</div>
						</div>
						<div className='tp-print-doctor'>
							Dr. Rajeshwar Sharma, MBBS, MD<br/>
							Reg No: GMC-12345<br/>
							Date: {new Date().toLocaleDateString('en-IN', {day: '2-digit', month: 'long', year: 'numeric'})}
						</div>
					</header>

					<div className='tp-print-section-title'>{TAB_TITLE[tab] || tab}</div>
					<div
						className='tp-print-content'
						dangerouslySetInnerHTML={{__html: html || '<p><em>No content.</em></p>'}}
					/>

					<footer className='tp-print-footer'>
						This document is electronically generated by VoiceRx and is valid without a physical signature.
					</footer>
				</div>
			</div>
		</div>
	)
}
